version: '3'

services:

  simple-user-profile-api:
    image: simple-user-profile-api
    ports:
      - "5555:8080"

  simple-user-profile-client:
    image: simple-user-profile-client
    environment:
      - PROFILE_API_URL=simple-user-profile-api:8080
    ports:
      - "4444:8080"